### ISSUE TITLE
libpq missing from mldb build

### ISSUE THREAD

**Issue by cmesse02** [mldbai/mldb#745]
Building the Community edition of mldb, at the "make compile" step, I got the following error:

      core/kernels/reader_base.pb_text.cc
      ./mldb/postgresql/postgresql_plugin.cc:14:33: fatal error: postgresql/libpq-fe.h: No such file or directory
       #include <postgresql/libpq-fe.h>
                                       ^
      compilation terminated.

I was able to work around the issue by doing:

   $ apt-get install libpq-dev

The rest of the build worked fine. However, when I ran the mldb docker container, I got the following errors:

    MLDB (version 2016.11.03.dev-1f737de) is starting up
    MldbServer [2016-11-03T14:49:27.077+00:00] error error loading plugin file:///opt/mldb/plugins/postgresql/: couldn't find plugin library '/opt/mldb/plugins/postgresql/lib/libmldb_postgresql_plugin.so': libpq.so.5: cannot open shared object file: No such file or directory
    MldbServer [2016-11-03T14:49:27.077+00:00] error plugin will be ignored

    MLDB ready

      File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/html5lib/treewalkers/etree.py", line 13
    from pip._vendor. import string_types
                               ^
    SyntaxError: invalid syntax

I built the mldb docker object after first building the Community versions of baseimage and mldb_base.

For reference, when I built the mldb docker object using the Enterprise versions of baseimage and mldb_base, there were no runtime errors.

I'm using Ubuntu 14.04.

**Comment by jraby** [comment]
Thanks for reporting this, I added the `libpq-dev` requirement to the list of required packages in the documentation.

The latest version of `mldb_base` does not include `libpq-dev` since the latest release of MLDB didn't include the postgresql plugin.
Unless you want to use this plugin right away, you can treat this message as a warning.

I'll double check for the python syntax error, I'm not sure where that comes from.

**Comment by jraby** [comment]
@cmesse02 What is the image id of the `mldb_base` image on which you're having the python error?

With the MLDB latest master (966ec8a51408dbde20d9cba3d080659ce8327868) and mldb_base:v2016.09.02.0  I can't reproduce the issue.

**Comment by cmesse02** [comment]
OK – thanks for the info. So things should be working fine, it sounds like.

When I connect to my mldb, I get the “Please activate MLDB with a license key” screen. I would have thought that I don’t need a license, since I’m using the Community version, built from scratch:

$ docker images
REPOSITORY                     TAG                                                                IMAGE ID            CREATED             SIZE
quay.io/datacratic/mldb        cmesse02-release_latest-1f737de3b4b808223e439b00d4165c0a8982225f   76ab9350ea4d        10 minutes ago      3.191 GB
quay.io/datacratic/mldb        cmesse02_latest                                                    76ab9350ea4d        10 minutes ago      3.191 GB
quay.io/datacratic/mldb_base   cmesse02_latest                                                    ba0f00d88a41        41 minutes ago      800.1 MB
quay.io/datacratic/baseimage   0.9.17                                                             d8964cb48295        About an hour ago   245.7 MB
ubuntu                         14.04                                                              1e0c3dd64ccd        2 weeks ago         187.9 MB

I run it with:

$ docker run --rm=true \
            -v /proj/mldb-test/mldb_data:/mldb_data \
            -e MLDB_IDS="$(id)" \
            -p 127.0.0.1:8080:80 \
            quay.io/datacratic/mldb:cmesse02_latest

Is there a way to build it so that you don’t need a license key to run it?

Thanks for looking into it.

-          Chuck

**Comment by cmesse02** [comment]
In response to jraby's second post...

The mldb_base image is a Community Edition version which I built from source, from https://github.com/mldbai/mldb.git. I sync'd the source yesterday.
