### ISSUE TITLE
Community edition is asking for license key

### ISSUE THREAD

**Issue by cmesse02** [mldbai/mldb#746]
From the documentation, "The MLDB Community Edition is a distribution of MLDB that can be built entirely from open-source software. The license is the Apache License v2.0...". This leads me to think that no license key is required to run the Community Edition.

By contrast, "The MLDB Enterprise Edition is a pre-built binary distribution of MLDB which includes the same software as the Community Edition plus the closed-source MLDB Pro Plugin. It is available under two license options: ...". Both license options require license keys.

I have built the Community Edition. When I connect to it, I get a screen asking for a license key.

**Comment by jraby** [comment]
Hi @cmesse02 sorry about that, can you try agin with the latest master?

**Comment by cmesse02** [comment]
I did a "git pull", and rebuilt docker_mldb. I'm still getting the same issue.
Next I'll try "make compile", then rebuild docker_mldb, and see if that works.

**Comment by jraby** [comment]
It is hard to see what is wrong with seeing the command you ran and their output.

Make sure you have commit 246fb0ff3924844d3775fb247554ef7bfc17129a and then run `make docker_mldb`

Once that's done, start mldb from the new docker image that was built.
If you can paste the last ~20 lines of output from `make docker_mldb`  and the `docker run` command you used, it would help me understand what is wrong.

**Comment by cmesse02** [comment]
Thanks! The issue was that I was on release_latest, rather than master.
I'm rebuilding now...

**Comment by cmesse02** [comment]
Using master, rather than release_latest, I see that I have commit 245fb0f. However, I now get a build error:

$ make compile
           [C++]                        mldb/sql/builtin_signal_functions.cc
./mldb/sql/builtin_signal_functions.cc:10:34: fatal error: mldb/ext/pffft/pffft.h: No such file or directory
 #include "mldb/ext/pffft/pffft.h"
                                  ^
compilation terminated.
make: *** [build/x86_64/obj/mldb/sql/builtin_signal_functions.cc.735936862e474097d6fce617376f10d5.lo] Error 1

**Comment by jraby** [comment]
Did you run `git submodule update --init` when changing branch?
`pffft` is a submodule and should be found under `mldb/ext/pffft`.

**Comment by cmesse02** [comment]
Yes, I had neglected to do that. Having done the submodule update, it now builds and runs.
Thanks for your help! Now it's time to try it out...

**Comment by jraby** [comment]
Alright.

btw, unless you want to tweak the code or develop new features, the easiest way to try it out is by going to https://mldb.ai and clicking the 'Try MLDB right now' button.
