### ISSUE TITLE
is this project still alive?

### ISSUE THREAD

**Issue by keogh** [mldbai/mldb#907]
the last commit was in oct 2018, is this still active and working?

**Comment by apatewp** [comment]
I got a 405 when trying to sign up on mldb.ai , unless stated by someone else i would assume it is dead.

**Comment by Sealteam56** [comment]
I as well would like to get a community edition as a docker container. Does anyone have a working container they could post?

**Comment by bonevays** [comment]
they removed the blog entry saying everything will be fine, so I guess nothing is fine or will ever be fine "MLDB will continue to be developed as an open source project, with the significantly expanded resources that Element AI has available. The Pro version of MLDB will also be open-sourced as will some plugins associated with the processing of LiDAR datasets. "

**Comment by jeremybarnes** [comment]
The project, as @bonevays says, didn't survive the MLDB acquisition as an active project, despite our best intentions.

Some of us still do the occasional bit of work on it, but it's very much a research and hobby project now, until further notice.

**Comment by ankostis** [comment]
Maybe someone with permissions should archive the project as a warning to newcomers, no?

Btw, the 3D-cube baked into the DB model is a very interesting take POV for storing & processing timeseries,
it's a pity this project got shelved :-(.
