### ISSUE TITLE
Reason to use / checkout mldb.ai in 2022?

### ISSUE THREAD

**Issue by Make42** [mldbai/mldb#964]
I got interested in the project after looking into the documentation. It seems the project is mostly abandoned - not only by companies, but also by volunteer. Is there any reason to still look into the system? What would be alternatives nowadays?

**Comment by jeremybarnes** [comment]
You're right: it's mostly abandoned, and the volunteer effort (me!) is more focused around improving the core architecture than maintaining the previous iteration.

There are many alternatives, but if I were you, I'd start with ClickHouse, Spark or H2O depending upon how important the database vs ML functionality is.
